INSERT INTO tb_member(nickname, provider_user_id, provider, region_type, email, gender, age_range) values('세미', '22012412', 'KAKAO', 'METROPOLITAN', 'ss@naver.com', 'MALE', '20');

INSERT INTO tb_subway_line(name, region_type) values('1호선', 'METROPOLITAN');
INSERT INTO tb_subway_line(name, region_type) values('2호선', 'METROPOLITAN');
INSERT INTO tb_subway_line(name, region_type) values('3호선', 'METROPOLITAN');
INSERT INTO tb_subway_line(name, region_type) values('4호선', 'METROPOLITAN');
INSERT INTO tb_subway_line(name, region_type) values('5호선', 'METROPOLITAN');
INSERT INTO tb_subway_line(name, region_type) values('6호선', 'METROPOLITAN');
INSERT INTO tb_subway_line(name, region_type) values('7호선', 'METROPOLITAN');
INSERT INTO tb_subway_line(name, region_type) values('8호선', 'METROPOLITAN');
INSERT INTO tb_subway_line(name, region_type) values('9호선', 'METROPOLITAN');

INSERT INTO tb_category(name) values('가방');
INSERT INTO tb_category(name) values('귀금속');
INSERT INTO tb_category(name) values('도서용품');
INSERT INTO tb_category(name) values('서류');
INSERT INTO tb_category(name) values('산업용품');
INSERT INTO tb_category(name) values('쇼핑백');
INSERT INTO tb_category(name) values('스포츠용품');
INSERT INTO tb_category(name) values('악기');
INSERT INTO tb_category(name) values('의류');
INSERT INTO tb_category(name) values('자동차');
INSERT INTO tb_category(name) values('전자기기');
INSERT INTO tb_category(name) values('지갑');
INSERT INTO tb_category(name) values('증명서');
INSERT INTO tb_category(name) values('컴퓨터');
INSERT INTO tb_category(name) values('카드');
INSERT INTO tb_category(name) values('현금');
INSERT INTO tb_category(name) values('휴대폰');
INSERT INTO tb_category(name) values('기타물품');
