ALTER TABLE tb_station
    MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_station
    MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_station
    MODIFY created_by VARCHAR(50) DEFAULT 'SYSTEM';

ALTER TABLE tb_station
    MODIFY updated_by VARCHAR(50) DEFAULT 'SYSTEM';
